export const Users = [
    {
      id:1,
      profilePicture: "/pp1.jpg",
      username: "Ahmed Azam ",
    },
    {
      id:2,
      profilePicture: "/pp2.jpg",
      username: "Onais Ahmed",
    },
    {
      id:3,
      profilePicture: "/pp 3.jpg",
      username: "Anas Khalid",
    },
    {
      id:4,
      profilePicture: "/pp 4.jpg",
      username: "Immad Hassan",
    },
    {
      id:5,
      profilePicture: "/pp 5.jpg",
      username: "Mohsin Khan ",
    },
    {
      id:6,
      profilePicture: "/pp 6.jpg",
      username: "Omer Khan ",
    },
    {
      id:7,
      profilePicture: "/pp 7.jpg",
      username: "Talha Ahmed ",
    },
    {
      id:8,
      profilePicture: "/pp1.jpg",
      username: "Shaheryar Ahmed ",
    },
    {
      id:9,
      profilePicture: "/pp 3.jpg",
      username: "Hammas Khan ",
    },
    {
      id:10,
      profilePicture: "/pp 5.jpg",
      username: "Shezil Khan ",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      name: "Hassan Khan",
      desc: "Love For All, Hatred For None.",
      photo: "post 1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      name: "Rehan Ahmed",
      photo: "post 2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      name: "Tasneem Shiekh",
      desc: "Every moment is a fresh beginning.",
      photo: "Posts\post 1.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      name: "Roger Joel",
      photo: "post 4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      name: "Bisma Murtaza",
      photo: "post 5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      name: "Haroon Khalif",
      photo: "post 1.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      name: "Mia Mohammad Khan",
      desc: "Never regret anything that made you smile.",
      photo: "post 3.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      name: "Samin Ansari ",
      photo: "post 2.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      name: "Bakhtawar Shiekh",
      desc: "Change the world by being yourself.",
      photo: "post 4.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      name: "Karim Khan",
      photo: "/post 2.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  